job_details:
  name: batch_size_comparison_big
  output_dir: exps
  num_gpus: 4
  num_nodes: 4
parameters:
    LIST_MODELS_ACC:
      - model: ['layers=8_hidden-dim=704']
        accum_freq: [1]
        batch_size: [4,8,12,16]
      - model: ['layers=23_hidden-dim=1024']
        accum_freq: [1]
        batch_size: [4,8,12]
      - model: ['layers=23_hidden-dim=1024']
        accum_freq: [2]
        batch_size: [16]
      - model: ['layers=26_hidden-dim=1312']
        accum_freq: [1]
        batch_size: [4]
      - model: ['layers=26_hidden-dim=1312']
        accum_freq: [2]
        batch_size: [8,12]
      - model: ['layers=26_hidden-dim=1312']
        accum_freq: [4]
        batch_size: [16]
    # model: ['layers=3_hidden-dim=96', 'layers=4_hidden-dim=128', 'layers=5_hidden-dim=160', 'layers=6_hidden-dim=244']
    train_num_samples: [100000000] # ~100M
    warmup: [200]
    
    dataset_resampled: [false]
    precision: ['amp_bfloat16']
    
    grad_checkpointing: [true]
    log_every_n_steps: [20]
    csv_log: [true]
    grad_clip_norm: [1]
    beta1: [0.9]
    beta2: [0.95]
    eps: [1.0e-08]
    report_to: ['wandb']
    resume: ['latest']
    data_key: ['json']
    lr_cooldown_end: [3.0e-05]
    qk_norm: [true]
    z_loss_coefficient: [0.0001]
    lr_scheduler: ['cosine']
    wd: [0.033]
    lr: [0.003]
    epochs: [1]
    wandb_project_name: ['lm_grid_160m_more_avgs']
    log_avg_model_training_loss: [20]
    delete_previous_checkpoint: [true]
    # keep_powers_of_two: [5]
    workers: [2]