job_details:
  name: CC_1_nodes_rw_BS_256_rerun
  output_dir: exps_final_runs
  num_gpus: 4
  num_nodes: 1
parameters:
    LIST_MODEL_TOKENS:
      - model: ['layers=3_hidden-dim=96']
        LIST_EPOCHS_BUDGET:
          - train_num_samples: [5033910]         
            warmup_tokens: [5173248] 
            epochs: [80, 40, 20, 10, 5]
          - train_num_samples: [2516955]            
            warmup_tokens: [2586624] 
            epochs: [5]
          # - train_num_samples: [1293312]
          #   warmup_tokens: [1293312] 
          #   epochs: [5]

      - model: ['layers=4_hidden-dim=128']
        LIST_EPOCHS_BUDGET:
          - train_num_samples: [6940861]         
            warmup_tokens: [7503872] 
            epochs: [80, 40, 20, 10, 5]
          - train_num_samples: [3470431]            
            warmup_tokens: [3751936] 
            epochs: [5]
          # - train_num_samples: [1875968] 
          #   warmup_tokens: [1875968] 
          #   epochs: [5]

      - model: ['layers=5_hidden-dim=160']
        LIST_EPOCHS_BUDGET:
          - train_num_samples: [10618503]
            warmup_tokens: [9809920] 
            epochs: [80, 40, 20, 10, 5]
          - train_num_samples: [5309252]
            warmup_tokens: [4904960] 
            epochs: [5]
          - train_num_samples: [2654626]            
            warmup_tokens: [2452480] 
            epochs: [5]

      - model: ['layers=6_hidden-dim=224']
        LIST_EPOCHS_BUDGET:
          - train_num_samples: [13356783]
            warmup_tokens: [15597568] 
            epochs: [80, 40, 20, 10, 5]
          - train_num_samples: [6678392]
            warmup_tokens: [7798784] 
            epochs: [5]
          - train_num_samples: [3339196]
            warmup_tokens: [3899392] 
            epochs: [5]
    
    max_checkpoints_flops: [1]
    lr: [3.0e-3]
    batch_size: [64]
    accum_freq: [4]
    lr_cooldown_end: [3.0e-5]
    beta2: [0.95]
    lr_scheduler: ['cosine']
    # beta2: [0.99]
    dataset_resampled: [false]
    precision: ['amp_bfloat16']
    grad_checkpointing: [true]
    log_every_n_steps: [20]
    csv_log: [true]
    grad_clip_norm: [1]
    beta1: [0.9]
    eps: [1.0e-08]
    report_to: ['wandb']
    resume: ['latest']
    data_key: ['json.gz']
    qk_norm: [true]
    z_loss_coefficient: [0.0001]
    log_avg_model_training_loss: [20]
    # decoupled_wd: [1.0e-4]
    wd: [0.033]
    wandb_project_name: ['lm_grid_160m_more_avgs']
    delete_previous_checkpoint: [true]
    workers: [2]
    flops_to_save: ['3.125e+15,6.250e+15,1.250e+16,2.500e+16,5.000e+16,1.000e+17,2.000e+17,4.000e+17,8.000e+17,1.600e+18,3.200e+18,6.400e+18,1.280e+19,2.560e+19,5.120e+19,1.024e+20']
    dataset_manifest: ["/p/data1/mmlaion/lmdata_2/refined_web_tokenized/manifest_train.jsonl"]
    # dataset_manifest: ["/p/data1/mmlaion/lmdata_2/openwebtext2_tokenized/manifest_train.jsonl"]
    multiple_data_passes: [true]
