job_details:
  name: CC_2_nodes_tuned_openwebtext2
  output_dir: exps_final_runs
  num_gpus: 4
  num_nodes: 2
parameters:
    LIST_MODEL_TOKENS:
      - model: ['layers=8_hidden-dim=288']
        warmup_tokens: [22487040] 
        accum_freq: [1]
        batch_size: [7]
        lr: [8.0e-03]
        lr_cooldown_end: [8.0e-05]
        lr_scheduler: ['cosine']
        averagers: ['none']
        LIST_EPOCHS_BUDGET:
          - train_num_samples: [9264596]
            max_checkpoints_flops: [3]
            epochs: [10]
          - train_num_samples: [18529192, 37058383, 74116766, 148233531]
            max_checkpoints_flops: [0]
            epochs: [10]

      - model: ['layers=9_hidden-dim=320']
        warmup_tokens: [28672000] 
        accum_freq: [1]
        batch_size: [8]
        lr: [5.1e-03]
        lr_cooldown_end: [5.1e-05]
        lr_scheduler: ['cosine']
        averagers: ['none']
        LIST_EPOCHS_BUDGET:
          - train_num_samples: [5011097]
            max_checkpoints_flops: [3]
            epochs: [29]
          - train_num_samples: [5812873, 11625745, 23251489, 46502977]
            max_checkpoints_flops: [0]
            epochs: [50]

      - model: ['layers=10_hidden-dim=384']
        warmup_tokens: [37060608] 
        accum_freq: [1]
        batch_size: [10]
        lr: [5.1e-03]
        lr_cooldown_end: [5.1e-05]
        lr_scheduler: ['cosine']
        averagers: ['none']
        LIST_SCHED_BUDGET:
          - train_num_samples: [4996820]            
            max_checkpoints_flops: [3]
            epochs: [45]
          - train_num_samples: [8994277, 17988552, 35977104, 71954208]
            max_checkpoints_flops: [0]
            epochs: [50]

      - model: ['layers=12_hidden-dim=480']
        warmup_tokens: [57384960] 
        accum_freq: [1]
        batch_size: [13]
        lr: [4.7e-03]
        lr_cooldown_end: [4.7e-05] 
        lr_scheduler: ['cosine']
        averagers: ['none']
        LIST_EPOCHS_BUDGET:
          - train_num_samples: [5808723]
            max_checkpoints_flops: [3]
            epochs: [50]
          - train_num_samples: [11617447, 23234892, 46469784, 92939567]
            max_checkpoints_flops: [0]
            epochs: [50]

    beta2: [0.99]
    dataset_resampled: [false]
    precision: ['amp_bfloat16']
    grad_checkpointing: [true]
    log_every_n_steps: [20]
    csv_log: [true]
    grad_clip_norm: [1]
    beta1: [0.9]
    eps: [1.0e-08]
    report_to: ['wandb']
    resume: ['latest']
    data_key: ['json.gz']
    qk_norm: [true]
    z_loss_coefficient: [0.0001]
    log_avg_model_training_loss: [20]
    decoupled_wd: [1.0e-4]
    wandb_project_name: ['lm_grid_160m_more_avgs']
    delete_previous_checkpoint: [true]
    workers: [2]
    flops_to_save: ['3.125e+15,6.250e+15,1.250e+16,2.500e+16,5.000e+16,1.000e+17,2.000e+17,4.000e+17,8.000e+17,1.600e+18,3.200e+18,6.400e+18,1.280e+19,2.560e+19,5.120e+19,1.024e+20']
    # dataset_manifest: ["/p/fastdata/mmlaion/lmdata_2/refined_web_tokenized/manifest_train.jsonl"]
    dataset_manifest: ["/p/fastdata/mmlaion/lmdata_2/openwebtext2_tokenized/manifest_train.jsonl"]
    multiple_data_passes: [true]