job_details:
  name: CC_8_nodes_big_BS
  output_dir: exps_final_runs
  num_gpus: 4
  num_nodes: 8
parameters:
    LIST_MODEL_TOKENS:
      - model: ['layers=18_hidden-dim=704']
        LIST_BUDGET_MAX_SAVE:
          - train_num_samples: [149045248]
            max_checkpoints_flops: [0]
            epochs: [80, 40, 20, 10, 5]
            warmup_tokens: [149045248] 
          - train_num_samples: [74522624]
            max_checkpoints_flops: [0]
            epochs: [5]
            warmup_tokens: [74522624] 
          - train_num_samples: [37261312]
            max_checkpoints_flops: [1]
            epochs: [5]
            warmup_tokens: [37261312]
        

      - model: ['layers=21_hidden-dim=832']
        LIST_BUDGET_MAX_SAVE:
          - train_num_samples: [220872704]
            max_checkpoints_flops: [0]
            epochs: [80, 40, 20, 10, 5]
            warmup_tokens: [220872704] 
          - train_num_samples: [110436352]
            max_checkpoints_flops: [0]
            epochs: [5]
            warmup_tokens: [110436352] 
          - train_num_samples: [55218176]
            max_checkpoints_flops: [1]
            epochs: [5]
            warmup_tokens: [55218176]

      - model: ['layers=23_hidden-dim=1024']
        LIST_BUDGET_MAX_SAVE:
          - train_num_samples: [347078656]
            max_checkpoints_flops: [0]
            epochs: [80, 40, 20, 10, 5]
            warmup_tokens: [347078656]
          - train_num_samples: [173539328]
            max_checkpoints_flops: [0]
            epochs: [50]
            warmup_tokens: [173539328] 
          - train_num_samples: [86769664]
            max_checkpoints_flops: [1]
            epochs: [25]
            warmup_tokens: [86769664] 

      - model: ['layers=26_hidden-dim=1120']
        LIST_BUDGET_MAX_SAVE:
          - train_num_samples: [455311360]
            max_checkpoints_flops: [0]
            epochs: [80, 40, 20, 10, 5]
            warmup_tokens: [455311360] 
          - train_num_samples: [227655680]
            max_checkpoints_flops: [0]
            epochs: [5]
            warmup_tokens: [227655680] 
          - train_num_samples: [113827840]
            max_checkpoints_flops: [1]
            epochs: [5]
            warmup_tokens: [113827840] 

      - model: ['layers=26_hidden-dim=1312']
        LIST_BUDGET_MAX_SAVE:
          - train_num_samples: [611958784]
            max_checkpoints_flops: [0]
            epochs: [80, 40, 20, 10, 5]
            warmup_tokens: [611958784] 
          - train_num_samples: [305979392]
            max_checkpoints_flops: [0]
            epochs: [5]
            warmup_tokens: [305979392] 
          - train_num_samples: [152989696]
            max_checkpoints_flops: [1]
            epochs: [5]
            warmup_tokens: [152989696] 

      - model: ['layers=30_hidden-dim=1504']
        LIST_BUDGET_MAX_SAVE:
          - train_num_samples: [901726208]
            max_checkpoints_flops: [0]
            epochs: [80, 40, 20, 10, 5]
            warmup_tokens: [901726208]
          - train_num_samples: [450863104]
            max_checkpoints_flops: [0]
            epochs: [5]
            warmup_tokens: [450863104]
          - train_num_samples: [225431552]
            max_checkpoints_flops: [1]
            epochs: [5]
            warmup_tokens: [225431552] 

    lr: [3.0e-3]
    batch_size: [8]
    lr_cooldown_end: [3.0e-5]
    beta2: [0.95]
    lr_scheduler: ['cosine']
    # beta2: [0.99]
    dataset_resampled: [false]
    precision: ['amp_bfloat16']
    grad_checkpointing: [true]
    log_every_n_steps: [20]
    csv_log: [true]
    grad_clip_norm: [1]
    beta1: [0.9]
    eps: [1.0e-08]
    report_to: ['wandb']
    resume: ['latest']
    data_key: ['json.gz']
    qk_norm: [true]
    z_loss_coefficient: [0.0001]
    log_avg_model_training_loss: [20]
    # decoupled_wd: [1.0e-4]
    wd: [0.033]
    wandb_project_name: ['lm_grid_160m_more_avgs']
    delete_previous_checkpoint: [true]
    workers: [2]
    flops_to_save: ['3.125e+15,6.250e+15,1.250e+16,2.500e+16,5.000e+16,1.000e+17,2.000e+17,4.000e+17,8.000e+17,1.600e+18,3.200e+18,6.400e+18,1.280e+19,2.560e+19,5.120e+19,1.024e+20']
    dataset_manifest: ["/p/fastdata/mmlaion/lmdata_2/refined_web_tokenized/manifest_train.jsonl"]
    # dataset_manifest: ["/p/fastdata/mmlaion/lmdata_2/openwebtext2_tokenized/manifest_train.jsonl"]
    multiple_data_passes: [true]