job_details:
  name: chinchilla_1_nodes
  output_dir: exps_final_runs
  num_gpus: 4
  num_nodes: 1
parameters:
    LIST_MODEL_TOKENS:
      - model: ['layers=3_hidden-dim=96']
        warmup_tokens: [5173248] 
        accum_freq: [1]
        batch_size: [5]
        lr: [1.3e-02]
        lr_cooldown_end: [1.3e-04]
        lr_scheduler: ['cosine']
        averagers: ['none']
        LIST_EPOCHS_BUDGET:
          - train_num_samples: [5033911]
            epochs: [5]
            max_checkpoints_flops: [4]
          - train_num_samples: [5033911, 10067822, 20135642, 40271283]
            epochs: [10]
            max_checkpoints_flops: [1]

      - model: ['layers=4_hidden-dim=128']
        warmup_tokens: [7503872] 
        accum_freq: [1]
        batch_size: [7]
        lr: [1.15e-02]
        lr_cooldown_end: [1.15e-04]
        lr_scheduler: ['cosine']
        averagers: ['none']
        LIST_EPOCHS_BUDGET:
          - train_num_samples: [4957758]            
            epochs: [7]
            max_checkpoints_flops: [4]
          - train_num_samples: [6940862, 13881723, 27763445, 55526889]            
            epochs: [10]
            max_checkpoints_flops: [1]

      - model: ['layers=5_hidden-dim=160']
        warmup_tokens: [9809920] 
        accum_freq: [1]
        batch_size: [8]
        lr: [1.05e-02]
        lr_scheduler: ['cosine']
        averagers: ['none']
        lr_cooldown_end: [1.05e-04]
        LIST_EPOCHS_BUDGET:
          - train_num_samples: [10618504, 21237007, 42474013, 84948026]          
            epochs: [10]
            max_checkpoints_flops: [1]
          - train_num_samples: [5309252]            
            epochs: [10]
            max_checkpoints_flops: [4]

      - model: ['layers=12_hidden-dim=480']
        warmup_tokens: [15597568] 
        accum_freq: [1]
        batch_size: [11]
        lr: [9.0e-03]
        lr_cooldown_end: [9.0e-05]
        lr_scheduler: ['cosine']
        averagers: ['none']
        LIST_EPOCHS_BUDGET:
          - train_num_samples: [13356784, 26713567, 53427133, 106854266]           
            epochs: [10]
            max_checkpoints_flops: [1]
          - train_num_samples: [6678392]
            epochs: [10]
            max_checkpoints_flops: [4]

    beta2: [0.99]
    dataset_resampled: [false]
    precision: ['amp_bfloat16']
    grad_checkpointing: [true]
    log_every_n_steps: [20]
    csv_log: [true]
    grad_clip_norm: [1]
    beta1: [0.9]
    eps: [1.0e-08]
    report_to: ['wandb']
    resume: ['latest']
    data_key: ['json.gz']
    qk_norm: [true]
    z_loss_coefficient: [0.0001]
    log_avg_model_training_loss: [20]
    decoupled_wd: [1.0e-4]
    wandb_project_name: ['lm_grid_160m_more_avgs']
    delete_previous_checkpoint: [true]
    workers: [2]
    flops_to_save: ['3.125e+15,6.250e+15,1.250e+16,2.500e+16,5.000e+16,1.000e+17,2.000e+17,4.000e+17,8.000e+17,1.600e+18,3.200e+18,6.400e+18,1.280e+19,2.560e+19,5.120e+19,1.024e+20']
    train_data: ["/p/fastdata/mmlaion/lmdata_2/refined_web_tokenized/{00001001..00042512}.tar"]