job_details:
  name: CC_8_nodes_owt2_BS_256_rerun_1_epoch
  output_dir: exps_final_runs
  num_gpus: 4
  num_nodes: 8
parameters:
    LIST_MODEL_TOKENS:
      - model: ['layers=18_hidden-dim=704']
        LIST_WARMUP:
          - cosine_half_period_tokens: [14313326740, 7156663370, 3578331685, 1789165842, 894582921]
            warmup_tokens: [149045248]
          - cosine_half_period_tokens: [447291460]
            warmup_tokens: [74522624] 
          - cosine_half_period_tokens: [223645730]
            warmup_tokens: [37261312] 

      - model: ['layers=21_hidden-dim=832']
        LIST_WARMUP:
          - cosine_half_period_tokens: [19317310800, 9658655400, 4829327700, 2414663850, 1207331925]
            warmup_tokens: [55218176]
          - cosine_half_period_tokens: [603665962]
            warmup_tokens: [27609088]
          - cosine_half_period_tokens: [301832981]
            warmup_tokens: [13804544]

      - model: ['layers=23_hidden-dim=1024']
        LIST_WARMUP:
          - cosine_half_period_tokens: [12293082840, 6146541420, 3073270710, 1536635355]
            warmup_tokens: [86769664]
          - cosine_half_period_tokens: [768317677]
            warmup_tokens: [43384832] 
          - cosine_half_period_tokens: [384158838]
            warmup_tokens: [21692416] 

      - model: ['layers=26_hidden-dim=1120']
        LIST_WARMUP:
          - cosine_half_period_tokens: [9370876820, 4685438410, 2342719205]
            warmup_tokens: [113827840]
          - cosine_half_period_tokens: [1171359602]
            warmup_tokens: [56913920] 
          - cosine_half_period_tokens: [585679801]
            warmup_tokens: [28456960] 

      - model: ['layers=26_hidden-dim=1312']
        LIST_WARMUP:
          - cosine_half_period_tokens: [6972147110, 3486073555]
            warmup_tokens: [611958784] 
          - cosine_half_period_tokens: [1743036777]
            warmup_tokens: [305979392]
          - cosine_half_period_tokens: [871518388]
            warmup_tokens: [152989696]

      - model: ['layers=30_hidden-dim=1504']
        LIST_WARMUP:
          - cosine_half_period_tokens: [4731665365]
            warmup_tokens: [901726208]
          - cosine_half_period_tokens: [2365832682]
            warmup_tokens: [450863104]
          - cosine_half_period_tokens: [1182916341]
            warmup_tokens: [225431552]

    # max_tokens is set to be cosine_half_period_tokens when it's not None + cosine_half_period_tokens is set
    train_num_samples: [21139292160]
    epochs: [1]
    max_checkpoints_flops: [1]
    lr: [3.0e-3]
    batch_size: [8]
    lr_cooldown_end: [3.0e-5]
    beta2: [0.95]
    lr_scheduler: ['cosine-target']
    # beta2: [0.99]
    dataset_resampled: [false]
    precision: ['amp_bfloat16']
    grad_checkpointing: [true]
    log_every_n_steps: [20]
    csv_log: [true]
    grad_clip_norm: [1]
    beta1: [0.9]
    eps: [1.0e-08]
    report_to: ['wandb']
    resume: ['latest']
    data_key: ['json.gz']
    qk_norm: [true]
    z_loss_coefficient: [0.0001]
    log_avg_model_training_loss: [20]
    # decoupled_wd: [1.0e-4]
    wd: [0.033]
    wandb_project_name: ['lm_grid_160m_more_avgs']
    delete_previous_checkpoint: [true]
    workers: [2]
    flops_to_save: ['3.125e+15,6.250e+15,1.250e+16,2.500e+16,5.000e+16,1.000e+17,2.000e+17,4.000e+17,8.000e+17,1.600e+18,3.200e+18,6.400e+18,1.280e+19,2.560e+19,5.120e+19,1.024e+20']
    # dataset_manifest: ["/p/fastdata/mmlaion/lmdata_2/refined_web_tokenized/manifest_train.jsonl"]
    dataset_manifest: ["/p/fastdata/mmlaion/lmdata_2/openwebtext2_tokenized/filtered_manifest_train.jsonl"]
    # multiple_data_passes: [true]