job_details:
  name: CC_8_nodes_orig_openwebtext2
  output_dir: exps_final_runs
  num_gpus: 4
  num_nodes: 8
parameters:
    LIST_MODEL_TOKENS:
      - model: ['layers=18_hidden-dim=704']
        warmup_tokens: [149045248] 
        LIST_BUDGET_MAX_SAVE:
            - train_num_samples: [8945830]
              max_checkpoints_flops: [3]
            - train_num_samples: [17891659, 35783317, 71566634, 143133268]
              max_checkpoints_flops: [0]
        

      - model: ['layers=21_hidden-dim=832']
        warmup_tokens: [220872704] 
        LIST_BUDGET_MAX_SAVE:
          - train_num_samples: [12073320]
            max_checkpoints_flops: [3]
          - train_num_samples: [24146639, 48293277, 96586554, 193173108]
            max_checkpoints_flops: [0]

      - model: ['layers=23_hidden-dim=1024']
        warmup_tokens: [347078656] 
        LIST_BUDGET_MAX_SAVE:
          - train_num_samples: [15366354]
            max_checkpoints_flops: [3]
          - train_num_samples: [30732708, 61465415, 122930829]
            max_checkpoints_flops: [0]

      - model: ['layers=26_hidden-dim=1120']
        warmup_tokens: [455311360] 
        LIST_BUDGET_MAX_SAVE:
          - train_num_samples: [23427193]
            max_checkpoints_flops: [3]
          - train_num_samples: [46854385, 93708769]
            max_checkpoints_flops: [0]

      - model: ['layers=26_hidden-dim=1312']
        warmup_tokens: [611958784] 
        LIST_BUDGET_MAX_SAVE:
          - train_num_samples: [34860736]
            max_checkpoints_flops: [3]
          - train_num_samples: [69721472]
            max_checkpoints_flops: [0]

      - model: ['layers=30_hidden-dim=1504']
        warmup_tokens: [901726208] 
        beta2: [0.95]
        LIST_BUDGET_MAX_SAVE:
          - train_num_samples: [47316654]
            max_checkpoints_flops: [3]

    lr: [6.0e-3]
    batch_size: [8]
    lr_cooldown_end: [6.0e-5]
    beta2: [0.95]
    lr_scheduler: ['cosine']
    # beta2: [0.99]
    dataset_resampled: [false]
    precision: ['amp_bfloat16']
    grad_checkpointing: [true]
    log_every_n_steps: [20]
    csv_log: [true]
    grad_clip_norm: [1]
    beta1: [0.9]
    eps: [1.0e-08]
    report_to: ['wandb']
    resume: ['latest']
    data_key: ['json.gz']
    qk_norm: [true]
    z_loss_coefficient: [0.0001]
    log_avg_model_training_loss: [20]
    # decoupled_wd: [1.0e-4]
    wd: [0.033]
    wandb_project_name: ['lm_grid_160m_more_avgs']
    delete_previous_checkpoint: [true]
    workers: [2]
    flops_to_save: ['3.125e+15,6.250e+15,1.250e+16,2.500e+16,5.000e+16,1.000e+17,2.000e+17,4.000e+17,8.000e+17,1.600e+18,3.200e+18,6.400e+18,1.280e+19,2.560e+19,5.120e+19,1.024e+20']
    # dataset_manifest: ["/p/fastdata/mmlaion/lmdata_2/refined_web_tokenized/manifest_train.jsonl"]
    dataset_manifest: ["/p/fastdata/mmlaion/lmdata_2/openwebtext2_tokenized/manifest_train.jsonl"]
    multiple_data_passes: [true]