job_details:
  name: chinchilla_long_runs_2_nodes
  output_dir: exps_final_runs
  num_gpus: 4
  num_nodes: 2
parameters:
    LIST_MODEL_TOKENS:
      - model: ['layers=8_hidden-dim=288']
        LIST_ROUND_MAX_CKPTS:
          - train_num_samples: [3705838] # ~3.7M
            max_checkpoints_flops: [5]
          - train_num_samples: [7411676, 14823352] # ~37.4M, 14.8M
            max_checkpoints_flops: [1]
        warmup_tokens: [1572864000, 13107200] # 1.57B, max(13.1M, 0.25*params) - kaplan warmup tokens and our warmup tokens

      - model: ['layers=9_hidden-dim=320']
        LIST_ROUND_MAX_CKPTS:
          - train_num_samples: [5812872] # ~5.8M
            max_checkpoints_flops: [5]
          - train_num_samples: [11625744, 23251488] # ~11.6M, 23.2M
            max_checkpoints_flops: [1]
        warmup_tokens: [1572864000, 13107200] 

      - model: ['layers=10_hidden-dim=384']
        LIST_ROUND_MAX_CKPTS:
          - train_num_samples: [8994275] # ~9M
            max_checkpoints_flops: [5]
          - train_num_samples: [17988550, 35977100] # ~18M, 36M
            max_checkpoints_flops: [1]
        warmup_tokens: [1572864000, 13107200] 

      - model: ['layers=12_hidden-dim=480']
        LIST_ROUND_MAX_CKPTS:
          - train_num_samples: [11617445] # ~11.6M
            max_checkpoints_flops: [5]
          - train_num_samples: [23234890, 46469780] # ~23.2M, 46.5M
            max_checkpoints_flops: [1]
        warmup_tokens: [1572864000, 14346240]

      - model: ['layers=14_hidden-dim=576']
        LIST_ROUND_MAX_CKPTS:
          - train_num_samples: [15725644] # ~15.7M
            max_checkpoints_flops: [5]
          - train_num_samples: [31451288, 62902576] # ~31.4M, 62.9M
            max_checkpoints_flops: [1]
        warmup_tokens: [1572864000, 21196800] 
        
      - model: ['layers=15_hidden-dim=640']
        LIST_ROUND_MAX_CKPTS:
          - train_num_samples: [24586165] # ~24.6M
            max_checkpoints_flops: [5]
          - train_num_samples: [49172330, 98344660] # ~49.2M, 98.3M
            max_checkpoints_flops: [1]
        warmup_tokens: [1572864000, 27115520] 
    
    dataset_resampled: [false]
    precision: ['amp_bfloat16']
    batch_size: [8] # global batch size is 8*2*4 = 64
    grad_checkpointing: [true]
    log_every_n_steps: [20]
    csv_log: [true]
    grad_clip_norm: [1]
    beta1: [0.9]
    beta2: [0.95]
    eps: [1.0e-08]
    report_to: ['wandb']
    resume: ['latest']
    data_key: ['json.gz']
    lr_cooldown_end: [3.0e-05] # in the rpj config it was like that, so I keep it
    qk_norm: [true]
    z_loss_coefficient: [0.0001]
    lr_scheduler: ['cosine']
    wd: [0.033]
    lr: [3.0e-03] 
    epochs: [100]
    wandb_project_name: ['lm_grid_160m_more_avgs']
    delete_previous_checkpoint: [true]
    workers: [2]
    accum_freq: [1]
    flops_to_save: ['3.125e+15,6.250e+15,1.250e+16,2.500e+16,5.000e+16,1.000e+17,2.000e+17,4.000e+17,8.000e+17,1.600e+18,3.200e+18,6.400e+18,1.280e+19,2.560e+19,5.120e+19,1.024e+20']
    train_data: ["/p/scratch/laionize/smyrnis1/refined_web_tokenized/{00001001..00042512}.tar"]
    # if there are 600B tokens in RW, and all of them are uniformly distributed in the shards, then each shard has 600B/42512 = 14.1M tokens
    # so, keeping 1000 shards for validation, we have 1000*14.1M = 14.1B tokens for validation