job_details:
  name: CC_2_nodes_tuned_short
  output_dir: exps_final_runs
  num_gpus: 4
  num_nodes: 2
parameters:
    LIST_MODEL_TOKENS:
      - model: ['layers=8_hidden-dim=288']
        accum_freq: [1]
        batch_size: [7]
        lr: [8.0e-03]
        lr_cooldown_end: [8.0e-05]
        epochs: [5]
        LIST_EPOCHS_BUDGET:
          - train_num_samples: [4632298] 
            max_checkpoints_flops: [1]
            warmup_tokens: [5621760] 
          - train_num_samples: [9264596] #4632298*2=9264596
            max_checkpoints_flops: [0]
            warmup_tokens: [11243520] 

      - model: ['layers=9_hidden-dim=320']
        accum_freq: [1]
        batch_size: [8]
        lr: [5.1e-03]
        lr_cooldown_end: [5.1e-05]
        epochs: [29]
        LIST_EPOCHS_BUDGET:
          - train_num_samples: [2505548] 
            max_checkpoints_flops: [0]
            warmup_tokens: [14336000] 
          - train_num_samples: [1252774] 
            max_checkpoints_flops: [1]
            warmup_tokens: [7168000] 

      - model: ['layers=10_hidden-dim=384']
        accum_freq: [1]
        batch_size: [10]
        lr: [5.1e-03]
        lr_cooldown_end: [5.1e-05]
        epochs: [45]
        LIST_SCHED_BUDGET:
          - train_num_samples: [2498410]
            max_checkpoints_flops: [0]
            warmup_tokens: [18530304] 
          - train_num_samples: [1249205]
            max_checkpoints_flops: [1]
            warmup_tokens: [9265152] 

      - model: ['layers=12_hidden-dim=480']
        accum_freq: [1]
        batch_size: [13]
        lr: [4.7e-03]
        lr_cooldown_end: [4.7e-05] 
        epochs: [25]
        LIST_EPOCHS_BUDGET:
          - train_num_samples: [2904361]
            max_checkpoints_flops: [1]
            warmup_tokens: [14346240] 
          - train_num_samples: [5808722] #2904361*2=5808722
            max_checkpoints_flops: [0]
            warmup_tokens: [28692480]

    lr_scheduler: ['cosine']
    beta2: [0.99]
    dataset_resampled: [false]
    precision: ['amp_bfloat16']
    grad_checkpointing: [true]
    log_every_n_steps: [20]
    csv_log: [true]
    grad_clip_norm: [1]
    beta1: [0.9]
    eps: [1.0e-08]
    report_to: ['wandb']
    resume: ['latest']
    data_key: ['json.gz']
    qk_norm: [true]
    z_loss_coefficient: [0.0001]
    log_avg_model_training_loss: [20]
    decoupled_wd: [1.0e-4]
    wandb_project_name: ['lm_grid_160m_more_avgs']
    delete_previous_checkpoint: [true]
    workers: [2]
    flops_to_save: ['3.125e+15,6.250e+15,1.250e+16,2.500e+16,5.000e+16,1.000e+17,2.000e+17,4.000e+17,8.000e+17,1.600e+18,3.200e+18,6.400e+18,1.280e+19,2.560e+19,5.120e+19,1.024e+20']
    dataset_manifest: ["/p/fastdata/mmlaion/lmdata_2/refined_web_tokenized/manifest_train.jsonl"]
    # dataset_manifest: ["/p/fastdata/mmlaion/lmdata_2/openwebtext2_tokenized/manifest_train.jsonl"]
    multiple_data_passes: [true]