job_details:
  name: const_1_nodes_tuned_openwebtext2
  output_dir: exps_final_runs
  num_gpus: 4
  num_nodes: 1
parameters:
    LIST_MODEL_TOKENS:
      - model: ['layers=3_hidden-dim=96']
        warmup_tokens: [5173248, 1572864000] 
        accum_freq: [1]
        batch_size: [5]
        lr: [1.3e-02]
        lr_cooldown_end: [1.3e-04]
        LIST_SCHED_BUDGET:
          - train_num_samples: [103464960]
            max_tokens: [500000000000] # holder for the max tokens (in submit_multiple all entries in LIST should have the same length)
            lr_scheduler: ['const']
            averagers: ['poly_08_1']
            epochs: [10]
          # - train_num_samples: [436906667]
          #   max_tokens: [1034649600]
          #   lr_scheduler: ['cosine']
          #   averagers: ['none']
          #   epochs: [300]

      - model: ['layers=4_hidden-dim=128']
        warmup_tokens: [7503872, 1572864000] 
        accum_freq: [1]
        batch_size: [7]
        lr: [1.15e-02]
        lr_cooldown_end: [1.15e-04]
        LIST_SCHED_BUDGET:
          - train_num_samples: [150077440]
            max_tokens: [500000000000] # holder for the max tokens (in submit_multiple all entries in LIST should have the same length)
            lr_scheduler: ['const']
            averagers: ['poly_08_1']
            epochs: [10]
          # - train_num_samples: [436906667]
          #   max_tokens: [1500774400]
          #   lr_scheduler: ['cosine']
          #   averagers: ['none']
          #   epochs: [300]

      - model: ['layers=5_hidden-dim=160']
        warmup_tokens: [9809920, 1572864000] 
        accum_freq: [1]
        batch_size: [8]
        lr: [1.05e-02]
        lr_cooldown_end: [1.05e-04]
        LIST_SCHED_BUDGET:
          - train_num_samples: [196198400]
            max_tokens: [500000000000] # holder for the max tokens (in submit_multiple all entries in LIST should have the same length)
            lr_scheduler: ['const']
            averagers: ['poly_08_1']
            epochs: [10]
          # - train_num_samples: [436906667]
          #   max_tokens: [1961984000]
          #   lr_scheduler: ['cosine']
          #   averagers: ['none']
          #   epochs: [300]

      - model: ['layers=6_hidden-dim=224']
        warmup_tokens: [15597568, 1572864000] 
        accum_freq: [1]
        batch_size: [11]
        lr: [9.0e-03]
        lr_cooldown_end: [9.0e-05]
        LIST_SCHED_BUDGET:
          - train_num_samples: [311951360]
            max_tokens: [500000000000]
            lr_scheduler: ['const']
            averagers: ['poly_08_1']
            epochs: [10]
          # - train_num_samples: [436906667]
          #   max_tokens: [3119513600]
          #   lr_scheduler: ['cosine']
          #   averagers: ['none']
          #   epochs: [300]

    beta2: [0.99]
    dataset_resampled: [false]
    precision: ['amp_bfloat16']
    grad_checkpointing: [true]
    log_every_n_steps: [20]
    csv_log: [true]
    grad_clip_norm: [1]
    beta1: [0.9]
    eps: [1.0e-08]
    report_to: ['wandb']
    resume: ['latest']
    data_key: ['json.gz']
    qk_norm: [true]
    z_loss_coefficient: [0.0001]
    log_avg_model_training_loss: [20]
    decoupled_wd: [1.0e-4]
    wandb_project_name: ['lm_grid_160m_more_avgs']
    delete_previous_checkpoint: [true]
    workers: [2]
    flops_to_save: ['3.125e+15,6.250e+15,1.250e+16,2.500e+16,5.000e+16,1.000e+17,2.000e+17,4.000e+17,8.000e+17,1.600e+18,3.200e+18,6.400e+18,1.280e+19,2.560e+19,5.120e+19,1.024e+20']
    max_checkpoints_flops: [9]
    # dataset_manifest: ["/p/fastdata/mmlaion/lmdata_2/refined_web_tokenized/manifest_train.jsonl"]
    dataset_manifest: ["/p/fastdata/mmlaion/lmdata_2/openwebtext2_tokenized/manifest_train.jsonl"]
    multiple_data_passes: [true]