job_details:
  name: const_long_runs_4_nodes
  output_dir: exps_final_runs
  num_gpus: 4
  num_nodes: 4
parameters:
    LIST_MODEL_TOKENS:
      - model: ['layers=18_hidden-dim=704']
        train_num_samples: [521658368] # ~522M - x100 epochs = 52.2B tokens (highest token count)
      - model: ['layers=21_hidden-dim=832']
        train_num_samples: [377291226] # ~377M - x100 epochs = 37.7B tokens it takes to reach 5e+19 flops
      - model: ['layers=23_hidden-dim=1024']
        train_num_samples: [240099274] # ~240M - x100 epochs = 24B tokens it takes to reach 5e+19 flops
      - model: ['layers=26_hidden-dim=1120']
        train_num_samples: [183024937] # ~183M - x100 epochs = 18.3B tokens it takes to reach 5e+19 flops 
      - model: ['layers=26_hidden-dim=1312']
        train_num_samples: [136174748] # ~136M - x100 epochs = 13.6B tokens it takes to reach 5e+19 flops
      - model: ['layers=30_hidden-dim=1504']
        train_num_samples: [92415339] # ~3.2B
    warmup_tokens: [1572864000, 13107200] # 1.57B, 13.1M - kaplan warmup tokens and our warmup tokens
    dataset_resampled: [false]
    precision: ['amp_bfloat16']
    batch_size: [4] # global batch size is 4*4*4 = 64
    grad_checkpointing: [true]
    log_every_n_steps: [20]
    csv_log: [true]
    grad_clip_norm: [1]
    beta1: [0.9]
    beta2: [0.95]
    eps: [1.0e-08]
    report_to: ['wandb']
    resume: ['latest']
    data_key: ['json.gz']
    qk_norm: [true]
    z_loss_coefficient: [0.0001]
    lr_scheduler: ['const']
    averagers: ['poly_16_1'] # add more averagers?
    log_avg_model_training_loss: [20] # if adding averagers, maybe increase this
    wd: [0.033]
    lr: [1.5e-03] 
    epochs: [100]
    wandb_project_name: ['lm_grid_160m_more_avgs']
    delete_previous_checkpoint: [true]
    workers: [2]
    accum_freq: [1]
    flops_to_save: ['3.125e+15,6.250e+15,1.250e+16,2.500e+16,5.000e+16,1.000e+17,2.000e+17,4.000e+17,8.000e+17,1.600e+18,3.200e+18,6.400e+18,1.280e+19,2.560e+19,5.120e+19,1.024e+20']
    max_checkpoints_flops: [6]
    train_data: ["/p/scratch/laionize/smyrnis1/refined_web_tokenized/{00001001..00042512}.tar"]
    # if there are 600B tokens in RW, and all of them are uniformly distributed in the shards, then each shard has 600B/42512 = 14.1M tokens
    # so, keeping 1000 shards for validation, we have 1000*14.1M = 14.1B tokens for validation