job_details:
  name: const_long_runs_8_nodes_BS_change
  output_dir: exps_final_runs
  num_gpus: 4
  num_nodes: 8
parameters:
    LIST_MODEL_TOKENS:
      - model: ['layers=18_hidden-dim=704']
        train_num_samples: [290739449] 
        warmup_tokens: [37261312] 
        accum_freq: [1]

      - model: ['layers=21_hidden-dim=832']
        train_num_samples: [196191437]
        warmup_tokens: [55218176]
        accum_freq: [1]

      - model: ['layers=23_hidden-dim=1024']
        train_num_samples: [124851622] 
        warmup_tokens: [86769664]
        accum_freq: [1]

      - model: ['layers=26_hidden-dim=1120']
        train_num_samples: [95172967] 
        warmup_tokens: [113827840]
        accum_freq: [2]

      - model: ['layers=26_hidden-dim=1312']
        train_num_samples: [70810869] 
        warmup_tokens: [152989696]
        accum_freq: [2]

      - model: ['layers=30_hidden-dim=1504']
        train_num_samples: [96111952] 
        warmup_tokens: [48055976]
        accum_freq: [2]

    
    dataset_resampled: [false]
    precision: ['amp_bfloat16']
    batch_size: [8] # global batch size is 4*4*16 = 256
    grad_checkpointing: [true]
    log_every_n_steps: [20]
    csv_log: [true]
    grad_clip_norm: [1]
    beta1: [0.9]
    beta2: [0.95]
    eps: [1.0e-08]
    report_to: ['wandb']
    resume: ['latest']
    data_key: ['json.gz']
    qk_norm: [true]
    z_loss_coefficient: [0.0001]
    lr_scheduler: ['const']
    averagers: ['poly_08_1']
    log_avg_model_training_loss: [20]
    wd: [0.033]
    lr: [3.0e-03] 
    epochs: [100]
    wandb_project_name: ['lm_grid_160m_more_avgs']
    delete_previous_checkpoint: [true]
    workers: [2]
    flops_to_save: ['5.000e+16,1.000e+17,2.000e+17,4.000e+17,8.000e+17,1.600e+18,3.200e+18,6.400e+18,1.280e+19,2.560e+19,5.120e+19,1.024e+20']
    max_checkpoints_flops: [40]
    train_data: ["/p/fastdata/mmlaion/lmdata_2/refined_web_tokenized/{00001001..00042512}.tar"]