job_details:
  name: final_sweep_const_extra_4
  output_dir: exps_sweep
  num_nodes: 4
  num_gpus: 4
parameters:
    LIST_ACC_BS:

      - model: ['layers=21_hidden-dim=832']
        train_num_samples: [441745408] 
        warmup_tokens: [441745408]
        LIST_BS_LR:
          - batch_size: [4]
            lr: [0.000375]
          - batch_size: [2]
            lr: [0.000375, 0.0001875]
        batch_size: [2, 4] # global batch size = 4*4*2 or 4*4*4 = 32 or 64

    accum_freq: [1]
    lr_cooldown_end: [0.0]
    decoupled_wd: [1.0e-4]
    lr_scheduler: ['const']
    averagers: ['poly_08_1'] 
    log_avg_model_training_loss: [20] 
    dataset_resampled: [false]
    precision: ['amp_bfloat16']
    grad_checkpointing: [true]
    log_every_n_steps: [20]
    csv_log: [true]
    grad_clip_norm: [1]
    beta1: [0.9]
    beta2: [0.95]
    eps: [1.0e-08]
    report_to: ['wandb']
    resume: ['latest']
    data_key: ['json.gz']
    
    qk_norm: [true]
    z_loss_coefficient: [0.0001]
    # wd: [0.033]
    epochs: [10]
    wandb_project_name: ['lm_grid_160m_more_avgs']
    log_avg_model_training_loss: [20]
    delete_previous_checkpoint: [true]
    # keep_freq: [5]
    # keep_from: [75]
    workers: [2]
    train_data: ["/p/scratch/laionize/smyrnis1/refined_web_tokenized/{00001001..00042512}.tar"]
    # flops_to_save: ['2.00e+15,4.00e+15,8.00e+15,1.60e+16,3.20e+16,6.40e+16,1.28e+17,2.56e+17,5.12e+17,1.02e+18,2.05e+18,4.10e+18,8.19e+18,1.64e+19,3.28e+19,6.55e+19']
    # max_checkpoints_flops: [5] 
