job_details:
  name: final_sweep_cosine_extra_4
  output_dir: exps_sweep
  num_nodes: 4
  num_gpus: 4
parameters:
    LIST_ACC_BS:

      - model: ['layers=21_hidden-dim=832']
        train_num_samples: [441745408] 
        warmup_tokens: [441745408]
        LIST_BS_LR:
          - batch_size: [4] # global batch size = 4*4*4 = 64
            lr: [7.5e-4]
            lr_cooldown_end: [7.5e-6]
          - batch_size: [2] # global batch size = 4*4*2 = 32
            LIST_LR_LR_COOLDOWN_END:
              - lr: [7.5e-4]
                lr_cooldown_end: [7.5e-6]
              - lr: [3.75e-4]
                lr_cooldown_end: [3.75e-6]


    accum_freq: [1]
    
    decoupled_wd: [1.0e-4]
    lr_scheduler: ['cosine']
    # warmup: [200]
    dataset_resampled: [false]
    precision: ['amp_bfloat16']
    grad_checkpointing: [true]
    log_every_n_steps: [20]
    csv_log: [true]
    grad_clip_norm: [1]
    beta1: [0.9]
    beta2: [0.95]
    eps: [1.0e-08]
    report_to: ['wandb']
    resume: ['latest']
    data_key: ['json.gz']
    qk_norm: [true]
    z_loss_coefficient: [0.0001]
    # wd: [0.033]
    epochs: [10]
    wandb_project_name: ['lm_grid_160m_more_avgs']
    log_avg_model_training_loss: [20]
    delete_previous_checkpoint: [true]
    workers: [2]
    train_data: ["/p/scratch/laionize/smyrnis1/refined_web_tokenized/{00001001..00042512}.tar"]
