job_details:
  name: final_sweep_cosine_extra_3
  output_dir: exps_sweep
  num_nodes: 4
  num_gpus: 4
parameters:
    LIST_ACC_BS:

      - model: ['layers=9_hidden-dim=320']
        train_num_samples: [57344000] 
        warmup_tokens: [57344000]
        batch_size: [8]

      - model: ['layers=12_hidden-dim=480']
        train_num_samples: [114769920] 
        warmup_tokens: [114769920]
        batch_size: [8, 16]

      - model: ['layers=15_hidden-dim=640']
        train_num_samples: [216924160] 
        warmup_tokens: [216924160]
        batch_size: [8, 16]

      - model: ['layers=21_hidden-dim=832']
        train_num_samples: [441745408] 
        warmup_tokens: [441745408]
        batch_size: [16]
        
    accum_freq: [1]
    
    LIST_LR_LR_COOLDOWN_END:
      - lr: [2.4e-2]
        lr_cooldown_end: [2.4e-4]
      - lr: [1.2e-2]
        lr_cooldown_end: [1.2e-4]
      - lr: [6.0e-3]
        lr_cooldown_end: [6.0e-5]
      - lr: [3.0e-3]
        lr_cooldown_end: [3.0e-5]
      - lr: [1.5e-3]
        lr_cooldown_end: [1.5e-5]
    decoupled_wd: [1.0e-4]
    lr_scheduler: ['cosine']
    # warmup: [200]
    dataset_resampled: [false]
    precision: ['amp_bfloat16']
    grad_checkpointing: [true]
    log_every_n_steps: [20]
    csv_log: [true]
    grad_clip_norm: [1]
    beta1: [0.9]
    beta2: [0.95]
    eps: [1.0e-08]
    report_to: ['wandb']
    resume: ['latest']
    data_key: ['json.gz']
    qk_norm: [true]
    z_loss_coefficient: [0.0001]
    # wd: [0.033]
    epochs: [10]
    wandb_project_name: ['lm_grid_160m_more_avgs']
    log_avg_model_training_loss: [20]
    delete_previous_checkpoint: [true]
    workers: [2]
    train_data: ["/p/scratch/laionize/smyrnis1/refined_web_tokenized/{00001001..00042512}.tar"]
