job_details:
  name: final_sweep_cosine
  output_dir: exps_sweep
  num_nodes: 1
  num_gpus: 4
parameters:
    LIST_ACC_BS:

      - model: ['layers=3_hidden-dim=96']
        train_num_samples: [10346496] # 10.34M, so x10 = 103.4M
        warmup_tokens: [10346496]

      - model: ['layers=4_hidden-dim=128']
        train_num_samples: [15007744] # 14.48M, so x10 = 144.8M
        warmup_tokens: [15007744]

      - model: ['layers=6_hidden-dim=224']
        train_num_samples: [31195136] # 19.22M, so x10 = 192.2M
        warmup_tokens: [31195136]

      - model: ['layers=9_hidden-dim=320']
        train_num_samples: [57344000] # 15.68M, so x10 = 156.8M
        warmup_tokens: [57344000] 

      - model: ['layers=12_hidden-dim=480']
        train_num_samples: [114769920] # 32.1M, so x10 = 321M
        warmup_tokens: [114769920]

      - model: ['layers=15_hidden-dim=640']
        train_num_samples: [216924160] 
        warmup_tokens: [216924160]

    accum_freq: [1]
    batch_size: [1, 2, 4, 8, 16]
    lr: [0.0015, 0.003, 0.006, 0.012, 0.024, 0.048]
    decoupled_wd: [1.0e-4]
    lr_scheduler: ['cosine']
    # warmup: [200]
    dataset_resampled: [false]
    precision: ['amp_bfloat16']
    grad_checkpointing: [true]
    log_every_n_steps: [20]
    csv_log: [true]
    grad_clip_norm: [1]
    beta1: [0.9]
    beta2: [0.95]
    eps: [1.0e-08]
    report_to: ['wandb']
    resume: ['latest']
    data_key: ['json.gz']
    lr_cooldown_end: [0.0]
    qk_norm: [true]
    z_loss_coefficient: [0.0001]
    # wd: [0.033]
    epochs: [10]
    wandb_project_name: ['lm_grid_160m_more_avgs']
    log_avg_model_training_loss: [20]
    delete_previous_checkpoint: [true]
    # keep_freq: [5]
    # keep_from: [75]
    workers: [2]
    train_data: ["/p/scratch/laionize/smyrnis1/refined_web_tokenized/{00001001..00042512}.tar"]
    # flops_to_save: ['2.00e+15,4.00e+15,8.00e+15,1.60e+16,3.20e+16,6.40e+16,1.28e+17,2.56e+17,5.12e+17,1.02e+18,2.05e+18,4.10e+18,8.19e+18,1.64e+19,3.28e+19,6.55e+19']
    # max_checkpoints_flops: [5] 
