job_details:
  name: final_sweep_const_extra_5
  output_dir: exps_sweep
  num_nodes: 4
  num_gpus: 4
parameters:
    LIST_MODELS:
      - model: ['layers=21_hidden-dim=832']
        train_num_samples: [441745408] 
        warmup_tokens: [441745408]
      - model: ['layers=15_hidden-dim=640']
        train_num_samples: [216924160] 
        warmup_tokens: [216924160]
    lr: [0.00075, 0.0015, 0.003, 0.006, 0.012, 0.024]
    LIST_BS_BETA2_MODELS:
      - batch_size: [16]
        accum_freq: [2]
        beta2: [0.99, 0.999]
      - batch_size: [32]
        accum_freq: [4]
        beta2: [0.95, 0.99, 0.999]
    decoupled_wd: [1.0e-4]
    lr_scheduler: ['const']
    averagers: ['poly_08_1'] 
    log_avg_model_training_loss: [20] 
    dataset_resampled: [false]
    precision: ['amp_bfloat16']
    grad_checkpointing: [true]
    log_every_n_steps: [20]
    csv_log: [true]
    grad_clip_norm: [1]
    beta1: [0.9]
    eps: [1.0e-08]
    report_to: ['wandb']
    resume: ['latest']
    data_key: ['json.gz']
    lr_cooldown_end: [0.0]
    qk_norm: [true]
    z_loss_coefficient: [0.0001]
    # wd: [0.033]
    epochs: [10]
    wandb_project_name: ['lm_grid_160m_more_avgs']
    log_avg_model_training_loss: [20]
    delete_previous_checkpoint: [true]
    # keep_freq: [5]
    # keep_from: [75]
    workers: [2]
    train_data: ["/p/data1/mmlaion/lmdata_2/refined_web_tokenized/{00001001..00042512}.tar"]