job_details:
  name: kaplan_2_nodes_orig
  output_dir: exps_final_runs
  num_gpus: 4
  num_nodes: 2
parameters:
    LIST_MODEL_TOKENS:
      - model: ['layers=8_hidden-dim=288']
        max_tokens: [449740800]
        warmup_tokens: [22487040, 1572864000] 

      - model: ['layers=9_hidden-dim=320']
        warmup_tokens: [28672000, 1572864000] 
        max_tokens: [573440000]
        warmup_tokens: [13107200]

      - model: ['layers=10_hidden-dim=384']
        warmup_tokens: [37060608, 1572864000] 
        warmup_tokens: [13107200]

      - model: ['layers=12_hidden-dim=480']
        warmup_tokens: [57384960, 1572864000] 
        max_tokens: [1147699200] 
        warmup_tokens: [14346240]
    
    train_num_samples: [436906667]
    dataset_resampled: [false]
    precision: ['amp_bfloat16']
    batch_size: [16] # global batch size is 16*2*4 = 128
    grad_checkpointing: [true]
    log_every_n_steps: [20]
    csv_log: [true]
    grad_clip_norm: [1]
    beta1: [0.9]
    beta2: [0.95]
    eps: [1.0e-08]
    report_to: ['wandb']
    resume: ['latest']
    data_key: ['json.gz']
    qk_norm: [true]
    z_loss_coefficient: [0.0001]
    lr_scheduler: ['cosine']
    log_avg_model_training_loss: [20] 
    wd: [0.033]
    lr: [2.12e-03] # change to 4.24e-03?
    epochs: [10]
    wandb_project_name: ['lm_grid_160m_more_avgs']
    delete_previous_checkpoint: [true]
    workers: [2]
    accum_freq: [1] # because of the annoying memory error
    flops_to_save: ['3.125e+15,6.250e+15,1.250e+16,2.500e+16,5.000e+16,1.000e+17,2.000e+17,4.000e+17,8.000e+17,1.600e+18,3.200e+18,6.400e+18,1.280e+19,2.560e+19,5.120e+19,1.024e+20']
    max_checkpoints_flops: [9]
    dataset_manifest: ["/p/fastdata/mmlaion/lmdata_2/refined_web_tokenized/manifest_train.jsonl"]