job_details:
  name: kaplan_8_nodes_openwebtext2
  output_dir: exps_final_runs
  num_gpus: 4
  num_nodes: 8
parameters:
    LIST_MODEL_TOKENS:
      - model: ['layers=18_hidden-dim=704']
        max_tokens: [29073944936] 
        warmup_tokens: [149045248, 1572864000] 

      - model: ['layers=21_hidden-dim=832']
        max_tokens: [19619143764]
        warmup_tokens: [55218176, 1572864000]

      - model: ['layers=23_hidden-dim=1024']
        max_tokens: [12485162249] 
        warmup_tokens: [220872704, 1572864000]

      - model: ['layers=26_hidden-dim=1120']
        max_tokens: [9517296764] 
        warmup_tokens: [455311360, 1572864000]

      - model: ['layers=26_hidden-dim=1312']
        max_tokens: [7081086908] 
        warmup_tokens: [611958784, 1572864000]

      - model: ['layers=30_hidden-dim=1504']
        max_tokens: [4805597636] 
        warmup_tokens: [901726208, 1572864000]

    train_num_samples: [436906667]
    dataset_resampled: [false]
    precision: ['amp_bfloat16']
    batch_size: [8]
    grad_checkpointing: [true]
    log_every_n_steps: [20]
    csv_log: [true]
    grad_clip_norm: [1]
    beta1: [0.9]
    beta2: [0.95]
    eps: [1.0e-08]
    report_to: ['wandb']
    resume: ['latest']
    data_key: ['json.gz']
    qk_norm: [true]
    z_loss_coefficient: [0.0001]
    lr_scheduler: ['cosine']
    log_avg_model_training_loss: [20]
    wd: [0.033]
    lr: [3.0e-03] 
    epochs: [300]
    wandb_project_name: ['lm_grid_160m_more_avgs']
    delete_previous_checkpoint: [true]
    workers: [2]
    accum_freq: [1]
    flops_to_save: ['3.125e+15,6.250e+15,1.250e+16,2.500e+16,5.000e+16,1.000e+17,2.000e+17,4.000e+17,8.000e+17,1.600e+18,3.200e+18,6.400e+18,1.280e+19,2.560e+19,5.120e+19,1.024e+20']
    max_checkpoints_flops: [9]
    # dataset_manifest: ["/p/fastdata/mmlaion/lmdata_2/refined_web_tokenized/manifest_train.jsonl"]
    dataset_manifest: ["/p/fastdata/mmlaion/lmdata_2/openwebtext2_tokenized/manifest_train.jsonl"]
    multiple_data_passes: [true]