job_details:
  name: long_runs_cosine_2_nodes
  output_dir: exps
  num_gpus: 4
  num_nodes: 2
parameters:
    model: ['layers=10_hidden-dim=384', 'layers=14_hidden-dim=576']
    train_num_samples: [426766791] # ~426M
    warmup: [200]
    accum_freq: [1]
    dataset_resampled: [false]
    precision: ['amp_bfloat16']
    batch_size: [16]
    grad_checkpointing: [true]
    log_every_n_steps: [20]
    csv_log: [true]
    grad_clip_norm: [1]
    beta1: [0.9]
    beta2: [0.95]
    eps: [1.0e-08]
    report_to: ['wandb']
    resume: ['latest']
    data_key: ['json']
    lr_cooldown_end: [3.0e-05]
    qk_norm: [true]
    z_loss_coefficient: [0.0001]
    lr_scheduler: ['cosine']
    wd: [0.033]
    lr: [0.00424]
    epochs: [64]
    wandb_project_name: ['lm_grid_160m_more_avgs']
    log_avg_model_training_loss: [20]
    delete_previous_checkpoint: [true]
    keep_powers_of_two: [5]
    workers: [2]