job_details:
  name: chinchilla_2_nodes_warmup_200
  output_dir: exps
  num_gpus: 4
  num_nodes: 2
parameters:
    LIST_OF_EPOCHS:
    - LIST_WARMUP_STEPS:
      - train_num_samples: [106691697] # ~107M
      - train_num_samples: [53345848] # ~53M
      model: ['layers=23_hidden-dim=1024']
      accum_freq: [2]
    - LIST_WARMUP_STEPS:
      - train_num_samples: [92090254] # ~92M
      - train_num_samples: [46045127] # ~46M
      - train_num_samples: [23022563] # ~23M
      model: ['layers=18_hidden-dim=704']
      accum_freq: [1]
    warmup: [200]
    dataset_resampled: [false]
    precision: ['amp_bfloat16']
    batch_size: [16]
    grad_checkpointing: [true]
    log_every_n_steps: [20]
    csv_log: [true]
    grad_clip_norm: [1]
    # warmup: [2000]
    beta1: [0.9]
    beta2: [0.95]
    eps: [1.0e-08]
    report_to: ['wandb']
    resume: ['latest']
    data_key: ['json']
    lr_cooldown_end: [3.0e-05]
    qk_norm: [true]
    z_loss_coefficient: [0.0001]
    lr_scheduler: ['cosine']
    wd: [0.033] # just smaller lr
    lr: [0.00424]
      # - wd: [0.1] # same multiplication as before
      #   lr: [0.002]
      # - wd: [0.1] # just bigger wd
      #   lr: [0.006]
    epochs: [64]
    wandb_project_name: ['lm_grid_160m_more_avgs']
    log_avg_model_training_loss: [20]
    delete_previous_checkpoint: [true]
    keep_powers_of_two: [5]
    workers: [2]