job_details:
  name: seed_variance_rerun
  output_dir: exps_final_runs
  num_nodes: 1
  num_gpus: 4
parameters:
    accum_freq: [1]
    beta2: [0.99]
    decoupled_wd: [1.0e-4]
    lr_scheduler: ['const']
    epochs: [10]
    LIST_SCHED_BUDGET:
      - train_num_samples: [10346496]
        model: ['layers=3_hidden-dim=96']
        batch_size: [5]
        lr: [1.3e-02]
        lr_cooldown_end: [1.3e-04]
        warmup_tokens: [5173248]
        accum_freq: [1]

      - train_num_samples: [15007744]
        model: ['layers=4_hidden-dim=128']
        batch_size: [7]
        lr: [1.15e-02]
        lr_cooldown_end: [1.15e-04]
        warmup_tokens: [7503872]
        accum_freq: [1]

      - train_num_samples: [19619840]
        model: ['layers=5_hidden-dim=160']
        batch_size: [8]
        lr: [1.05e-02]
        lr_cooldown_end: [1.05e-04]
        warmup_tokens: [9809920]
        accum_freq: [1]

      - train_num_samples: [311951360]
        model: ['layers=6_hidden-dim=224']
        batch_size: [11]
        lr: [9.0e-03]
        lr_cooldown_end: [9.0e-05]
        warmup_tokens: [15597568]
        accum_freq: [1]

      - train_num_samples: [573440000]
        model: ['layers=9_hidden-dim=320']
        batch_size: [16]
        lr: [7.4e-03]
        lr_cooldown_end: [7.4e-05]
        warmup_tokens: [28672000]
        accum_freq: [1]

      - train_num_samples: [1147699200]
        model: ['layers=12_hidden-dim=480']
        batch_size: [26]
        lr: [1.05e-02]
        lr_cooldown_end: [1.05e-04]
        warmup_tokens: [57384960]
        accum_freq: [2]


    dataset_resampled: [false]
    precision: ['amp_bfloat16']
    grad_checkpointing: [true]
    log_every_n_steps: [20]
    csv_log: [true]
    grad_clip_norm: [1]
    beta1: [0.9]
    eps: [1.0e-08]
    report_to: ['wandb']
    resume: ['latest']
    data_key: ['json.gz']
    qk_norm: [true]
    z_loss_coefficient: [0.0001]
    wandb_project_name: ['lm_grid_160m_more_avgs']
    log_avg_model_training_loss: [20]
    delete_previous_checkpoint: [true]
    workers: [2]
    dataset_manifest: ["/p/fastdata/mmlaion/lmdata_2/refined_web_tokenized/manifest_train.jsonl"]
    flops_to_save: ['2.00e+15,4.00e+15,8.00e+15,1.60e+16,3.20e+16,6.40e+16,1.28e+17,2.56e+17,5.12e+17,1.02e+18,2.05e+18,4.10e+18,8.19e+18,1.64e+19,3.28e+19,6.55e+19']
    max_checkpoints_flops: [3]

    seed: [1, 2, 3, 4, 5, 6, 7]