job_details:
  name: sidekick_runs_sparse_averaging_laionize
  output_dir: exps
  num_gpus: 4
  num_nodes: 2
parameters:
    model: ['layers=14_hidden-dim=576'] # 86M params
    accum_freq: [1]
    warmup: [1000]
    dataset_resampled: [false]
    precision: ['amp_bfloat16']
    batch_size: [3] # running on 2 nodes with 4 GPUs each, so global batch size = 24
    grad_checkpointing: [true]
    csv_log: [true]
    grad_clip_norm: [1]
    wd: [0.33]
    lr_scheduler: ['cosine'] # option 1
    averagers: ['poly_16_100,poly_16_1000,poly_16_3000,poly_16_6000']
    train_num_samples: [400000000] # 400M, so *100 = 40B tokens
    beta1: [0.9]
    beta2: [0.95]
    eps: [1.0e-08]
    log_avg_model_training_loss: [20]
    report_to: ['wandb']
    resume: ['latest']
    data_key: ['json.gz'] # using the new shards - changed train_data config in slurm script
    lr_cooldown_end: [0.0]
    qk_norm: [true]
    z_loss_coefficient: [0.0001]
    lr: [3.0e-04]
    epochs: [100]
    wandb_project_name: ['lm_grid_160m_more_avgs']
    log_every_n_steps: [20]
    delete_previous_checkpoint: [true]
    keep_freq: [5]
    keep_from: [75]
    workers: [2]
    # train_data: ["['/p/scratch/ccstdl/smyrnis1/rw_v2_fasttext_openhermes_vs_rw_v2_bigram_0.1/{00000005..00001747}.tar']"]