job_details:
  name: sidekick_runs_eval
  output_dir: exps
parameters:
    model: ['layers=14_hidden-dim=576']
    dataset_resampled: [false]
    precision: ['amp_bfloat16']
    batch_size: [8]
    grad_checkpointing: [true]
    log_every_n_steps: [1]
    grad_clip_norm: [1]
    resume: [
      'exps/24-04-03-sidekick_runs_debug/012_24-04-03-sidekick_runs_debug+lr=0.003+tra_num_sam=400000000+lr_sch=cosine/checkpoints/epoch_74.pt'
      ]
    data_key: ['json']
    qk_norm: [true]
    workers: [2]
    averagers: ['poly_64_1', 'none']
    train_num_samples: [400000000]