job_details:
  name: sidekick_runs_eval
  output_dir: exps
parameters:
    model: ['layers=14_hidden-dim=576']
    dataset_resampled: [false]
    precision: ['amp_bfloat16']
    batch_size: [8]
    grad_checkpointing: [true]
    log_every_n_steps: [1]
    grad_clip_norm: [1]
    resume: [
      'exps/24-04-05-cosine_warmup_v2/000_24-04-05-cosine_warmup_v2+/checkpoints/epoch_100.pt',
      'exps/24-04-04-cosine_warmup/000_24-04-04-cosine_warmup+/checkpoints/epoch_100.pt',
      'exps/24-04-05-sidekick_runs_rerun_const/000_24-04-05-sidekick_runs_rerun_const+/checkpoints/epoch_100.pt',
      'exps/24-04-05-sidekick_runs_rerun_const/000_24-04-05-sidekick_runs_rerun_const+/checkpoints/epoch_74.pt',
      'exps/24-04-04-sidekick_runs_rerun_cooldown/000_24-04-04-sidekick_runs_rerun_cooldown+tra_num_sam=400000000+epo_coo=5+lr_sch=const-cooldown+lr=0.0015/checkpoints/epoch_100.pt',
      'exps/24-04-04-sidekick_runs_rerun_cooldown/001_24-04-04-sidekick_runs_rerun_cooldown+tra_num_sam=400000000+epo_coo=5+lr_sch=hybrid-cooldown+lr=0.003/checkpoints/epoch_100.pt',
      'exps/24-04-04-sidekick_runs_rerun_cooldown/002_24-04-04-sidekick_runs_rerun_cooldown+tra_num_sam=385000000+epo_coo=5+lr_sch=const-cooldown+lr=0.0015/checkpoints/epoch_100.pt',
      'exps/24-04-04-sidekick_runs_rerun_cooldown/003_24-04-04-sidekick_runs_rerun_cooldown+tra_num_sam=385000000+epo_coo=5+lr_sch=hybrid-cooldown+lr=0.003/checkpoints/epoch_100.pt',
      'exps/24-04-04-sidekick_runs_rerun_cooldown/004_24-04-04-sidekick_runs_rerun_cooldown+tra_num_sam=400000000+epo_coo=10+lr_sch=const-cooldown+lr=0.0015/checkpoints/epoch_100.pt',
      'exps/24-04-04-sidekick_runs_rerun_cooldown/005_24-04-04-sidekick_runs_rerun_cooldown+tra_num_sam=400000000+epo_coo=10+lr_sch=hybrid-cooldown+lr=0.003/checkpoints/epoch_100.pt',
      'exps/24-04-04-sidekick_runs_rerun_cooldown/006_24-04-04-sidekick_runs_rerun_cooldown+tra_num_sam=300000000+epo_coo=30+lr_sch=const-cooldown+lr=0.0015/checkpoints/epoch_100.pt',
      'exps/24-04-04-sidekick_runs_rerun_cooldown/007_24-04-04-sidekick_runs_rerun_cooldown+tra_num_sam=300000000+epo_coo=30+lr_sch=hybrid-cooldown+lr=0.003/checkpoints/epoch_100.pt',
      'exps/24-04-04-sidekick_runs_rerun_cooldown/008_24-04-04-sidekick_runs_rerun_cooldown+tra_num_sam=340000000+epo_coo=20+lr_sch=const-cooldown+lr=0.0015/checkpoints/epoch_100.pt',
      'exps/24-04-04-sidekick_runs_rerun_cooldown/009_24-04-04-sidekick_runs_rerun_cooldown+tra_num_sam=340000000+epo_coo=20+lr_sch=hybrid-cooldown+lr=0.003/checkpoints/epoch_100.pt',
      'exps/24-04-04-sidekick_runs_rerun_cooldown/010_24-04-04-sidekick_runs_rerun_cooldown+tra_num_sam=370000000+epo_coo=10+lr_sch=const-cooldown+lr=0.0015/checkpoints/epoch_100.pt',
      'exps/24-04-04-sidekick_runs_rerun_cooldown/011_24-04-04-sidekick_runs_rerun_cooldown+tra_num_sam=370000000+epo_coo=10+lr_sch=hybrid-cooldown+lr=0.003/checkpoints/epoch_100.pt',
      'exps/24-04-04-sidekick_runs_rerun_cooldown/012_24-04-04-sidekick_runs_rerun_cooldown+tra_num_sam=400000000+epo_coo=20+lr_sch=const-cooldown+lr=0.0015/checkpoints/epoch_100.pt',
      'exps/24-04-04-sidekick_runs_rerun_cooldown/013_24-04-04-sidekick_runs_rerun_cooldown+tra_num_sam=400000000+epo_coo=20+lr_sch=hybrid-cooldown+lr=0.003/checkpoints/epoch_100.pt',
      'exps/24-04-04-sidekick_runs_rerun_cooldown/014_24-04-04-sidekick_runs_rerun_cooldown+tra_num_sam=300000000+epo_coo=5+lr_sch=const-cooldown+lr=0.0015/checkpoints/epoch_100.pt',
      'exps/24-04-04-sidekick_runs_rerun_cooldown/015_24-04-04-sidekick_runs_rerun_cooldown+tra_num_sam=300000000+epo_coo=5+lr_sch=hybrid-cooldown+lr=0.003/checkpoints/epoch_100.pt',
      'exps/24-04-04-sidekick_runs_rerun_cooldown/016_24-04-04-sidekick_runs_rerun_cooldown+tra_num_sam=300000000+epo_coo=10+lr_sch=const-cooldown+lr=0.0015/checkpoints/epoch_100.pt',
      'exps/24-04-04-sidekick_runs_rerun_cooldown/017_24-04-04-sidekick_runs_rerun_cooldown+tra_num_sam=300000000+epo_coo=10+lr_sch=hybrid-cooldown+lr=0.003/checkpoints/epoch_100.pt',
      'exps/24-04-04-sidekick_runs_rerun_cooldown/018_24-04-04-sidekick_runs_rerun_cooldown+tra_num_sam=300000000+epo_coo=20+lr_sch=const-cooldown+lr=0.0015/checkpoints/epoch_100.pt',
      'exps/24-04-04-sidekick_runs_rerun_cooldown/019_24-04-04-sidekick_runs_rerun_cooldown+tra_num_sam=300000000+epo_coo=20+lr_sch=hybrid-cooldown+lr=0.003/checkpoints/epoch_100.pt',
      'exps/24-04-04-sidekick_runs_rerun_cooldown/020_24-04-04-sidekick_runs_rerun_cooldown+tra_num_sam=400000000+epo_coo=30+lr_sch=const-cooldown+lr=0.0015/checkpoints/epoch_100.pt',
      'exps/24-04-04-sidekick_runs_rerun_cooldown/021_24-04-04-sidekick_runs_rerun_cooldown+tra_num_sam=400000000+epo_coo=30+lr_sch=hybrid-cooldown+lr=0.003/checkpoints/epoch_100.pt',
      ]
    data_key: ['json']
    qk_norm: [true]
    workers: [2]
    averagers: ['poly_32_1', 'none']
    train_num_samples: [400000000]