job_details:
  name: sidekick_runs_eval
  output_dir: exps
parameters:
    model: ['layers=14_hidden-dim=576']
    dataset_resampled: [false]
    precision: ['amp_bfloat16']
    batch_size: [8]
    grad_checkpointing: [true]
    log_every_n_steps: [1]
    grad_clip_norm: [1]
    resume: [
      'exps/24-04-03-sidekick_runs_debug/000_24-04-03-sidekick_runs_debug+lr=0.003+tra_num_sam=385000000+lr_sch=const-cooldown/checkpoints/epoch_100.pt',
      'exps/24-04-03-sidekick_runs_debug/001_24-04-03-sidekick_runs_debug+lr=0.00424+tra_num_sam=385000000+lr_sch=const-cooldown/checkpoints/epoch_100.pt', 
      'exps/24-04-03-sidekick_runs_debug/006_24-04-03-sidekick_runs_debug+lr=0.003+tra_num_sam=300000000+lr_sch=const-cooldown/checkpoints/epoch_100.pt',
      'exps/24-04-03-sidekick_runs_debug/007_24-04-03-sidekick_runs_debug+lr=0.00424+tra_num_sam=300000000+lr_sch=const-cooldown/checkpoints/epoch_100.pt',
      'exps/24-04-03-sidekick_runs_debug/008_24-04-03-sidekick_runs_debug+lr=0.003+tra_num_sam=400000000+lr_sch=const/checkpoints/epoch_100.pt',
      'exps/24-04-03-sidekick_runs_debug/008_24-04-03-sidekick_runs_debug+lr=0.003+tra_num_sam=400000000+lr_sch=const/checkpoints/epoch_74.pt',
      'exps/24-04-03-sidekick_runs_debug/009_24-04-03-sidekick_runs_debug+lr=0.00424+tra_num_sam=400000000+lr_sch=const/checkpoints/epoch_100.pt',
      'exps/24-04-03-sidekick_runs_debug/009_24-04-03-sidekick_runs_debug+lr=0.00424+tra_num_sam=400000000+lr_sch=const/checkpoints/epoch_74.pt',
      'exps/24-04-03-sidekick_runs_debug/010_24-04-03-sidekick_runs_debug+lr=0.003+tra_num_sam=400000000+lr_sch=hybrid/checkpoints/epoch_100.pt',
      'exps/24-04-03-sidekick_runs_debug/010_24-04-03-sidekick_runs_debug+lr=0.003+tra_num_sam=400000000+lr_sch=hybrid/checkpoints/epoch_74.pt',
      'exps/24-04-03-sidekick_runs_debug/011_24-04-03-sidekick_runs_debug+lr=0.00424+tra_num_sam=400000000+lr_sch=hybrid/checkpoints/epoch_100.pt',
      'exps/24-04-03-sidekick_runs_debug/011_24-04-03-sidekick_runs_debug+lr=0.00424+tra_num_sam=400000000+lr_sch=hybrid/checkpoints/epoch_74.pt',
      'exps/24-04-03-sidekick_runs_debug/012_24-04-03-sidekick_runs_debug+lr=0.003+tra_num_sam=400000000+lr_sch=cosine/checkpoints/epoch_100.pt',
      'exps/24-04-03-sidekick_runs_debug/013_24-04-03-sidekick_runs_debug+lr=0.00424+tra_num_sam=400000000+lr_sch=cosine/checkpoints/epoch_100.pt',
      'exps/24-04-03-sidekick_runs_debug/014_24-04-03-sidekick_runs_debug+lr=0.003+tra_num_sam=300000000+lr_sch=cosine/checkpoints/epoch_100.pt',
      'exps/24-04-03-sidekick_runs_debug/015_24-04-03-sidekick_runs_debug+lr=0.00424+tra_num_sam=300000000+lr_sch=cosine/checkpoints/epoch_100.pt'
      ]
    data_key: ['json']
    qk_norm: [true]
    workers: [2]
    # averagers: [ 'none']
    train_num_samples: [400000000]